‎BOT_TOKEN = "8501866882:AAFLjFY-x6svgvnvCeTlNx2_lSpmf91rFtg"
‎BOT_USERNAME = "CINEMZOBOT"
‎BOT_LINK = "https://t.me/CINEMZOBOT"
‎CHANNEL_USERNAME = "@cinemzo_com"
‎CHANNEL_LINK = "https://t.me/cinemzo_com"
‎WEBAPP_URL = "https://cinemzo-com.blogspot.com/?m=1#home-page"
